#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Canonical vocabulary source v1.

Purpose
-------
Convert the materialized HSK runtime (hsk_1..8 + lookup + summaries) into a
compact, normalized source representation and regenerate a runtime-compatible
snapshot from that source.

Phase B1 is BASELINE-ONLY: it must preserve the semantic content of the
verified repo baseline. It does not ingest new XieHanzi data.

The compact source removes the largest structural duplication:
- one canonical base payload per word;
- per-level payload deltas only when a level differs;
- one metadata row per lesson/topic/membership section;
- level membership order is implicit in compact level arrays;
- route references store only section index, order-in-section, and optional
  provenance source code;
- quick lookup is generated by policy plus a small compatibility override set.
"""
from __future__ import annotations

import argparse
import copy
import gzip
import hashlib
import json
import re
import shutil
from collections import defaultdict
from pathlib import Path
from typing import Any

SCHEMA = "canonical-vocab-source-v1"
BASELINE_COMMIT = "2acc4540"
WORD_SHARDS = 64
LIBRARY_REGISTRY = ["hsk", "new_hsk", "yct", "boya"]
SECTION_FIELDS = [
    "libraryId", "libraryName", "levelNo", "levelId", "levelName",
    "sectionType", "sectionOrder", "sectionId", "sectionSlug",
    "sectionTitle", "sectionTitleZh", "sectionUrl",
]
DEFAULT_MEMORY_TIPS = {
    "characterStructure": {"explanation": []},
    "commonWords": [],
}
STANDARD_PAYLOAD_FIELDS = [
    "word", "simplified", "traditional", "pinyin", "meaningVi",
    "translationVi", "wordType", "wordTypeExplanation", "usageNote",
    "charCount", "chars", "audioUrls", "examples", "collocations",
    "components", "memoryTips",
]
RUNTIME_FILES = [
    *(f"hsk_{i}.json" for i in range(1, 9)),
    "hsk_flashcard_lookup.json",
    "hsk_summary.json",
    "source_summary.json",
]


def canonical_json_bytes(obj: Any) -> bytes:
    return json.dumps(obj, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode("utf-8")


def compact_json_bytes(obj: Any) -> bytes:
    return (json.dumps(obj, ensure_ascii=False, separators=(",", ":")) + "\n").encode("utf-8")


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def semantic_hash(obj: Any) -> str:
    return sha256_bytes(canonical_json_bytes(obj))


def read_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8-sig"))


def write_compact_json(path: Path, obj: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(compact_json_bytes(obj))


def write_pretty_json(path: Path, obj: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(obj, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def norm_word(v: Any) -> str:
    return v.replace("\u200b", "").replace("\ufeff", "").strip() if isinstance(v, str) else ""


def strip_dynamic(item: dict[str, Any]) -> dict[str, Any]:
    return {k: copy.deepcopy(v) for k, v in item.items() if k not in ("libraries", "routes")}


def diff_payload(base: dict[str, Any], variant: dict[str, Any]) -> dict[str, Any]:
    sets: dict[str, Any] = {}
    deletes: list[str] = []
    for k in sorted(set(base) | set(variant)):
        if k not in variant:
            deletes.append(k)
        elif k not in base or base[k] != variant[k]:
            sets[k] = copy.deepcopy(variant[k])
    out: dict[str, Any] = {}
    if sets:
        out["set"] = sets
    if deletes:
        out["delete"] = deletes
    return out


def apply_delta(base: dict[str, Any], delta: dict[str, Any]) -> dict[str, Any]:
    out = copy.deepcopy(base)
    for k in delta.get("delete", []):
        out.pop(k, None)
    for k, v in delta.get("set", {}).items():
        out[k] = copy.deepcopy(v)
    return out


def select_base_variant(variants: list[tuple[int, dict[str, Any]]]) -> tuple[int, dict[str, Any]]:
    payloads = [(level, strip_dynamic(item)) for level, item in variants]
    best = None
    for level, candidate in payloads:
        cost = sum(len(canonical_json_bytes(diff_payload(candidate, other))) for _, other in payloads)
        key = (cost, -len(canonical_json_bytes(candidate)), level)
        if best is None or key < best[0]:
            best = (key, level, candidate)
    if best is None:
        raise RuntimeError("select_base_variant called with no variants")
    return best[1], best[2]


def compact_base_payload(word: str, payload: dict[str, Any]) -> dict[str, Any]:
    q = copy.deepcopy(payload)
    if q.get("word") == word:
        q.pop("word", None)
    if q.get("simplified") == word:
        q.pop("simplified", None)
    if q.get("traditional") == word:
        q.pop("traditional", None)
    for k, default in (
        ("wordTypeExplanation", ""),
        ("usageNote", ""),
        ("audioUrls", []),
        ("examples", []),
        ("collocations", []),
        ("components", []),
    ):
        if q.get(k) == default:
            q.pop(k, None)
    if q.get("memoryTips") == DEFAULT_MEMORY_TIPS:
        q.pop("memoryTips", None)
    if "translationVi" in q and q.get("translationVi") == q.get("meaningVi"):
        q.pop("translationVi")
    return q


def expand_base_payload(word: str, compact: dict[str, Any]) -> dict[str, Any]:
    p = copy.deepcopy(compact)
    p["word"] = word
    p["simplified"] = p.get("simplified", word)
    p["traditional"] = p.get("traditional", word)
    if "translationVi" not in p:
        p["translationVi"] = p.get("meaningVi", "")
    p.setdefault("wordTypeExplanation", "")
    p.setdefault("usageNote", "")
    p.setdefault("audioUrls", [])
    p.setdefault("examples", [])
    p.setdefault("collocations", [])
    p.setdefault("components", [])
    p.setdefault("memoryTips", copy.deepcopy(DEFAULT_MEMORY_TIPS))
    # Stable runtime key order for readable/debuggable generated JSON.
    out: dict[str, Any] = {}
    for k in STANDARD_PAYLOAD_FIELDS:
        if k in p:
            out[k] = p[k]
    for k, v in p.items():
        if k not in out:
            out[k] = v
    return out


def load_runtime(runtime_dir: Path) -> tuple[dict[int, dict[str, Any]], dict[str, Any], dict[str, Any], dict[str, Any]]:
    missing = [name for name in RUNTIME_FILES if not (runtime_dir / name).is_file()]
    if missing:
        raise RuntimeError(f"Missing runtime files in {runtime_dir}: {missing}")
    docs = {i: read_json(runtime_dir / f"hsk_{i}.json") for i in range(1, 9)}
    for level, doc in docs.items():
        if not isinstance(doc, dict) or not isinstance(doc.get("items"), list):
            raise RuntimeError(f"Invalid hsk_{level}.json")
        seen: set[str] = set()
        for n, item in enumerate(doc["items"], 1):
            word = norm_word(item.get("word") or item.get("simplified"))
            if not word:
                raise RuntimeError(f"hsk_{level} item {n} missing word")
            if word in seen:
                raise RuntimeError(f"duplicate word inside hsk_{level}: {word}")
            seen.add(word)
    return (
        docs,
        read_json(runtime_dir / "hsk_flashcard_lookup.json"),
        read_json(runtime_dir / "hsk_summary.json"),
        read_json(runtime_dir / "source_summary.json"),
    )


def default_lookup_entry(candidates: list[tuple[int, dict[str, Any], dict[str, Any]]]) -> dict[str, Any]:
    c = sorted(candidates, key=lambda t: (
        0 if t[2].get("libraryId") == "hsk" else 1,
        t[0],
        0 if t[2].get("sectionType") in ("lesson", "topic") else 1,
        int(t[2].get("sectionOrder") or 999999),
        int(t[2].get("orderInSection") or 999999),
    ))
    level, item, route = c[0]
    word = norm_word(item.get("word"))
    return {
        "word": word,
        "pinyin": re.sub(r"\s+", " ", str(item.get("pinyin") or "").replace("*", " ").strip()),
        "meaningVi": str(item.get("meaningVi") or "").strip(),
        "libraryId": str(route.get("libraryId") or ""),
        "levelNo": level,
        "sectionTitle": str(route.get("sectionTitle") or ""),
    }


def build_source(runtime_dir: Path, output_dir: Path, baseline_commit: str = BASELINE_COMMIT) -> dict[str, Any]:
    docs, lookup, hsk_summary, source_summary = load_runtime(runtime_dir)
    if output_dir.exists():
        shutil.rmtree(output_dir)
    output_dir.mkdir(parents=True)

    variants: dict[str, list[tuple[int, dict[str, Any]]]] = defaultdict(list)
    for level in range(1, 9):
        for item in docs[level]["items"]:
            variants[norm_word(item.get("word"))].append((level, item))

    word_records: list[list[Any]] = []
    for word in sorted(variants):
        base_level, base_payload = select_base_variant(variants[word])
        overrides: list[list[Any]] = []
        for level, item in sorted(variants[word], key=lambda x: x[0]):
            delta = diff_payload(base_payload, strip_dynamic(item))
            if delta:
                overrides.append([level, delta])
        rec: list[Any] = [word, base_level, compact_base_payload(word, base_payload)]
        if overrides:
            rec.append(overrides)
        word_records.append(rec)

    # Normalize route metadata at section granularity. Current verified data has
    # one stable metadata object per sectionId; only orderInSection/source vary.
    section_by_id: dict[str, dict[str, Any]] = {}
    route_source_values: list[str] = []
    for level in range(1, 9):
        for item in docs[level]["items"]:
            for route in item.get("routes", []):
                if not isinstance(route, dict):
                    raise RuntimeError(f"Non-object route for {item.get('word')} in level {level}")
                meta = {k: copy.deepcopy(v) for k, v in route.items() if k not in ("orderInSection", "source")}
                sid = str(meta.get("sectionId") or "")
                if not sid:
                    raise RuntimeError(f"route missing sectionId for {item.get('word')} level {level}")
                if sid in section_by_id and section_by_id[sid] != meta:
                    raise RuntimeError(f"Conflicting metadata for sectionId={sid}")
                section_by_id[sid] = meta
                if "source" in route and route["source"] not in route_source_values:
                    route_source_values.append(route["source"])

    section_ids = sorted(section_by_id)
    section_index = {sid: i for i, sid in enumerate(section_ids)}
    sections = [[section_by_id[sid].get(k) for k in SECTION_FIELDS] for sid in section_ids]
    source_index = {s: i + 1 for i, s in enumerate(route_source_values)}
    lib_code = {s: i for i, s in enumerate(LIBRARY_REGISTRY)}

    levels: dict[str, list[list[Any]]] = {}
    library_order_overrides = 0
    total_route_refs = 0
    for level in range(1, 9):
        rows: list[list[Any]] = []
        for item in docs[level]["items"]:
            refs: list[list[Any]] = []
            derived_libraries: list[str] = []
            for route in item.get("routes", []):
                ref: list[Any] = [section_index[route["sectionId"]], route.get("orderInSection")]
                if "source" in route:
                    ref.append(source_index[route["source"]])
                refs.append(ref)
                total_route_refs += 1
                lib = route.get("libraryId")
                if lib and lib not in derived_libraries:
                    derived_libraries.append(lib)
            row: list[Any] = [norm_word(item.get("word")), refs]
            if derived_libraries != item.get("libraries", []):
                try:
                    row.append([lib_code[x] for x in item.get("libraries", [])])
                except KeyError as exc:
                    raise RuntimeError(f"Unknown library in {item.get('libraries')}: {exc}") from exc
                library_order_overrides += 1
            rows.append(row)
        levels[str(level)] = rows

    headers = {str(level): {k: copy.deepcopy(v) for k, v in docs[level].items() if k != "items"} for level in range(1, 9)}

    # Quick lookup: derive the common policy and persist only compatibility
    # exceptions where the historically verified selection differs.
    eligible: dict[str, list[tuple[int, dict[str, Any], dict[str, Any]]]] = defaultdict(list)
    for level in range(1, 9):
        for item in docs[level]["items"]:
            word = norm_word(item.get("word"))
            for route in item.get("routes", []):
                if isinstance(route, dict) and route.get("libraryId") in ("hsk", "new_hsk"):
                    eligible[word].append((level, item, route))
    lookup_items = lookup.get("items", {}) if isinstance(lookup.get("items"), dict) else {}
    if set(eligible) != set(lookup_items):
        raise RuntimeError(
            f"Quick lookup key set does not equal eligible HSK/New-HSK word set: "
            f"eligible={len(eligible)} lookup={len(lookup_items)} diff={len(set(eligible)^set(lookup_items))}"
        )
    lookup_overrides: dict[str, dict[str, Any]] = {}
    for word in sorted(eligible):
        derived = default_lookup_entry(eligible[word])
        if derived != lookup_items[word]:
            lookup_overrides[word] = copy.deepcopy(lookup_items[word])

    manifest = {
        "schemaVersion": SCHEMA,
        "baselineCommit": baseline_commit,
        "wordShardCount": WORD_SHARDS,
        "counts": {
            "uniqueWords": len(word_records),
            "materializedMemberships": sum(len(v) for v in levels.values()),
            "sections": len(sections),
            "routeRefs": total_route_refs,
            "libraryOrderOverrides": library_order_overrides,
            "quickLookupOverrides": len(lookup_overrides),
            "quickLookupItems": len(lookup_items),
        },
        "libraryRegistry": LIBRARY_REGISTRY,
        "routeSourceValues": route_source_values,
        "sectionFields": SECTION_FIELDS,
        "formats": {
            "wordRecord": "[word,baseFromLevel,compactBasePayload,optionalOverrides[[level,delta],...]]",
            "levelRecord": "[word,routeRefs,optionalLibraryOrderCodes]",
            "routeRef": "[sectionIndex,orderInSection,optionalSourceIndex1Based]",
        },
        "baseDefaults": {
            "word": "outer word",
            "simplified": "outer word",
            "traditional": "outer word",
            "translationVi": "meaningVi",
            "wordTypeExplanation": "",
            "usageNote": "",
            "audioUrls": [],
            "examples": [],
            "collocations": [],
            "components": [],
            "memoryTips": DEFAULT_MEMORY_TIPS,
        },
        "runtimeSemanticHashes": {
            **{f"hsk_{i}.json": semantic_hash(docs[i]) for i in range(1, 9)},
            "hsk_flashcard_lookup.json": semantic_hash(lookup),
            "hsk_summary.json": semantic_hash(hsk_summary),
            "source_summary.json": semantic_hash(source_summary),
        },
    }

    write_compact_json(output_dir / "manifest.json", manifest)
    write_compact_json(output_dir / "sections.json", sections)
    write_compact_json(output_dir / "levels.json", levels)
    write_compact_json(output_dir / "runtime_headers.json", headers)
    write_compact_json(output_dir / "lookup_overrides.json", lookup_overrides)
    # Baseline-only metadata templates. These files are small and preserve all
    # source/status provenance while the large runtime item payloads are normalized.
    write_compact_json(output_dir / "hsk_summary_template.json", hsk_summary)
    write_compact_json(output_dir / "source_summary_template.json", source_summary)

    shards: dict[int, list[list[Any]]] = defaultdict(list)
    for rec in word_records:
        shard = hashlib.sha256(rec[0].encode("utf-8")).digest()[0] >> 2
        shards[shard].append(rec)
    for i in range(WORD_SHARDS):
        write_compact_json(output_dir / "words" / f"{i:02x}.json", shards[i])

    return manifest


def load_source(source_dir: Path) -> tuple[dict[str, Any], dict[str, dict[str, Any]], dict[tuple[str, int], dict[str, Any]], list[dict[str, Any]], dict[str, list[list[Any]]], dict[str, Any], dict[str, Any], dict[str, Any], dict[str, Any]]:
    manifest = read_json(source_dir / "manifest.json")
    if manifest.get("schemaVersion") != SCHEMA:
        raise RuntimeError(f"Unsupported source schema: {manifest.get('schemaVersion')}")
    shard_count = int(manifest.get("wordShardCount") or 0)
    if shard_count != WORD_SHARDS:
        raise RuntimeError(f"Expected {WORD_SHARDS} word shards, got {shard_count}")

    base_by_word: dict[str, dict[str, Any]] = {}
    overrides: dict[tuple[str, int], dict[str, Any]] = {}
    for i in range(WORD_SHARDS):
        p = source_dir / "words" / f"{i:02x}.json"
        rows = read_json(p)
        if not isinstance(rows, list):
            raise RuntimeError(f"Invalid word shard {p}")
        for rec in rows:
            if not isinstance(rec, list) or len(rec) < 3:
                raise RuntimeError(f"Invalid word record in {p}: {rec!r}")
            word, _base_level, compact = rec[:3]
            if word in base_by_word:
                raise RuntimeError(f"Duplicate canonical word: {word}")
            base_by_word[word] = expand_base_payload(word, compact)
            if len(rec) > 3:
                for level, delta in rec[3]:
                    overrides[(word, int(level))] = delta

    rows = read_json(source_dir / "sections.json")
    fields = manifest.get("sectionFields")
    if fields != SECTION_FIELDS:
        raise RuntimeError("sectionFields do not match v1 contract")
    sections = [{k: v for k, v in zip(SECTION_FIELDS, row)} for row in rows]
    levels = read_json(source_dir / "levels.json")
    headers = read_json(source_dir / "runtime_headers.json")
    lookup_overrides = read_json(source_dir / "lookup_overrides.json")
    hsk_summary = read_json(source_dir / "hsk_summary_template.json")
    source_summary = read_json(source_dir / "source_summary_template.json")
    return manifest, base_by_word, overrides, sections, levels, headers, lookup_overrides, hsk_summary, source_summary


def generate_runtime(source_dir: Path, output_dir: Path, pretty: bool = False) -> dict[str, Any]:
    manifest, base_by_word, overrides, sections, levels, headers, lookup_overrides, hsk_summary, source_summary = load_source(source_dir)
    if output_dir.exists():
        shutil.rmtree(output_dir)
    output_dir.mkdir(parents=True)

    source_values = manifest.get("routeSourceValues", [])
    library_registry = manifest.get("libraryRegistry", [])
    docs: dict[int, dict[str, Any]] = {}
    writer = write_pretty_json if pretty else write_compact_json

    for level in range(1, 9):
        header = copy.deepcopy(headers[str(level)])
        items: list[dict[str, Any]] = []
        seen: set[str] = set()
        for row in levels[str(level)]:
            word, refs = row[:2]
            if word in seen:
                raise RuntimeError(f"Duplicate word in canonical level {level}: {word}")
            seen.add(word)
            if word not in base_by_word:
                raise RuntimeError(f"Unknown canonical word in level {level}: {word}")
            payload = apply_delta(base_by_word[word], overrides.get((word, level), {}))
            routes: list[dict[str, Any]] = []
            derived_libraries: list[str] = []
            for ref in refs:
                section_idx = int(ref[0])
                if section_idx < 0 or section_idx >= len(sections):
                    raise RuntimeError(f"Invalid section index {section_idx} for {word}")
                route = copy.deepcopy(sections[section_idx])
                route["orderInSection"] = ref[1]
                if len(ref) > 2:
                    source_idx = int(ref[2]) - 1
                    if source_idx < 0 or source_idx >= len(source_values):
                        raise RuntimeError(f"Invalid route source index for {word}: {ref}")
                    route["source"] = source_values[source_idx]
                routes.append(route)
                lib = route.get("libraryId")
                if lib and lib not in derived_libraries:
                    derived_libraries.append(lib)
            libraries = derived_libraries
            if len(row) > 2:
                libraries = [library_registry[int(code)] for code in row[2]]
            payload["libraries"] = libraries
            payload["routes"] = routes
            items.append(payload)
        header["items"] = items
        docs[level] = header
        writer(output_dir / f"hsk_{level}.json", header)

    # Generate quick lookup from policy + compatibility exceptions.
    eligible: dict[str, list[tuple[int, dict[str, Any], dict[str, Any]]]] = defaultdict(list)
    for level in range(1, 9):
        for item in docs[level]["items"]:
            word = norm_word(item.get("word"))
            for route in item.get("routes", []):
                if isinstance(route, dict) and route.get("libraryId") in ("hsk", "new_hsk"):
                    eligible[word].append((level, item, route))
    items = {word: default_lookup_entry(eligible[word]) for word in sorted(eligible)}
    for word, value in lookup_overrides.items():
        if word not in items:
            raise RuntimeError(f"lookup override is no longer eligible: {word}")
        items[word] = copy.deepcopy(value)

    # Preserve top-level lookup metadata from the verified baseline. We only
    # reconstruct the large items object.
    baseline_lookup_meta = {
        "schemaVersion": "hsk-flashcard-lookup-v1",
        "generatedFrom": "data/learning/hsk/hsk_1..8.json",
        "priority": ["hsk", "new_hsk"],
        "count": len(items),
        "items": items,
        "candidateBuild": {
            "schemaVersion": "canonical-vocab-candidate-v1",
            "policy": "preserve-existing-append-only",
        },
    }
    # Do not silently assume metadata if baseline differs. The semantic hash
    # below will catch it, but fail earlier with a clearer message if possible.
    expected_lookup_hash = manifest.get("runtimeSemanticHashes", {}).get("hsk_flashcard_lookup.json")
    if expected_lookup_hash and semantic_hash(baseline_lookup_meta) != expected_lookup_hash:
        raise RuntimeError("Generated quick lookup does not match baseline semantic hash")
    writer(output_dir / "hsk_flashcard_lookup.json", baseline_lookup_meta)
    writer(output_dir / "hsk_summary.json", hsk_summary)
    writer(output_dir / "source_summary.json", source_summary)

    hashes = {
        **{f"hsk_{i}.json": semantic_hash(docs[i]) for i in range(1, 9)},
        "hsk_flashcard_lookup.json": semantic_hash(baseline_lookup_meta),
        "hsk_summary.json": semantic_hash(hsk_summary),
        "source_summary.json": semantic_hash(source_summary),
    }
    expected_hashes = manifest.get("runtimeSemanticHashes", {})
    hash_mismatches = {name: {"expected": expected_hashes.get(name), "actual": value}
                       for name, value in hashes.items()
                       if expected_hashes.get(name) and expected_hashes.get(name) != value}
    if hash_mismatches:
        raise RuntimeError(f"Generated runtime semantic hashes differ from canonical manifest: {hash_mismatches}")
    return {
        "schemaVersion": "canonical-vocab-runtime-build-v1",
        "sourceSchema": SCHEMA,
        "format": "pretty" if pretty else "compact",
        "semanticHashes": hashes,
        "totalRecords": sum(len(docs[i]["items"]) for i in range(1, 9)),
        "uniqueWords": len({item["word"] for i in range(1, 9) for item in docs[i]["items"]}),
        "lookupCount": len(items),
    }


def verify(source_dir: Path, baseline_runtime_dir: Path, generated_dir: Path, report_path: Path | None = None) -> dict[str, Any]:
    baseline_docs, baseline_lookup, baseline_hsum, baseline_ssum = load_runtime(baseline_runtime_dir)
    build = generate_runtime(source_dir, generated_dir, pretty=False)
    generated_docs, generated_lookup, generated_hsum, generated_ssum = load_runtime(generated_dir)

    issues: list[dict[str, Any]] = []
    pairs: list[tuple[str, Any, Any]] = [
        *((f"hsk_{i}.json", baseline_docs[i], generated_docs[i]) for i in range(1, 9)),
        ("hsk_flashcard_lookup.json", baseline_lookup, generated_lookup),
        ("hsk_summary.json", baseline_hsum, generated_hsum),
        ("source_summary.json", baseline_ssum, generated_ssum),
    ]
    per_file = []
    for name, old, new in pairs:
        oh = semantic_hash(old)
        nh = semantic_hash(new)
        equal = old == new
        per_file.append({"file": name, "semanticEqual": equal, "baselineSemanticSha256": oh, "generatedSemanticSha256": nh})
        if not equal:
            issues.append({"file": name, "code": "SEMANTIC_MISMATCH"})

    expected = read_json(source_dir / "manifest.json").get("runtimeSemanticHashes", {})
    for row in per_file:
        e = expected.get(row["file"])
        if e and e != row["baselineSemanticSha256"]:
            issues.append({"file": row["file"], "code": "BASELINE_DIFFERS_FROM_SOURCE_MANIFEST", "expected": e, "actual": row["baselineSemanticSha256"]})

    # Idempotency: generate a second time and compare bytes for all runtime files.
    second_dir = generated_dir.parent / (generated_dir.name + "_repeat")
    generate_runtime(source_dir, second_dir, pretty=False)
    idempotency_diffs = []
    for name in RUNTIME_FILES:
        a = generated_dir / name
        b = second_dir / name
        if a.read_bytes() != b.read_bytes():
            idempotency_diffs.append(name)
    shutil.rmtree(second_dir, ignore_errors=True)
    if idempotency_diffs:
        issues.append({"code": "IDEMPOTENCY_FAILURE", "files": idempotency_diffs})

    source_files = [p for p in source_dir.rglob("*") if p.is_file()]
    runtime_files = [baseline_runtime_dir / name for name in RUNTIME_FILES]
    generated_files = [generated_dir / name for name in RUNTIME_FILES]
    source_raw = sum(p.stat().st_size for p in source_files)
    runtime_raw = sum(p.stat().st_size for p in runtime_files)
    generated_raw = sum(p.stat().st_size for p in generated_files)
    source_gz = sum(len(gzip.compress(p.read_bytes(), compresslevel=9)) for p in source_files)
    runtime_gz = sum(len(gzip.compress(p.read_bytes(), compresslevel=9)) for p in runtime_files)
    generated_gz = sum(len(gzip.compress(p.read_bytes(), compresslevel=9)) for p in generated_files)

    report = {
        "schemaVersion": "canonical-vocab-source-v1-verification",
        "status": "PASS" if not issues else "FAIL",
        "baselineCommit": BASELINE_COMMIT,
        "sourceSchema": SCHEMA,
        "semanticIssues": issues,
        "files": per_file,
        "idempotencyByteDifferences": idempotency_diffs,
        "counts": {
            "totalRecords": build["totalRecords"],
            "uniqueWords": build["uniqueWords"],
            "lookupCount": build["lookupCount"],
        },
        "size": {
            "trackedRuntimeCurrentRawBytes": runtime_raw,
            "canonicalSourceRawBytes": source_raw,
            "rawBytesSavedIfRuntimeUntracked": runtime_raw - source_raw,
            "rawPercentSaved": round((runtime_raw - source_raw) * 100 / runtime_raw, 4) if runtime_raw else 0,
            "trackedRuntimeCurrentGzip9EstimateBytes": runtime_gz,
            "canonicalSourceGzip9EstimateBytes": source_gz,
            "gzip9EstimateBytesSaved": runtime_gz - source_gz,
            "gzip9EstimatePercentSaved": round((runtime_gz - source_gz) * 100 / runtime_gz, 4) if runtime_gz else 0,
            "generatedCompactPagesRuntimeRawBytes": generated_raw,
            "generatedCompactPagesRuntimeVsCurrentSavedBytes": runtime_raw - generated_raw,
            "generatedCompactPagesRuntimeVsCurrentPercentSaved": round((runtime_raw - generated_raw) * 100 / runtime_raw, 4) if runtime_raw else 0,
            "generatedCompactPagesRuntimeGzip9EstimateBytes": generated_gz,
        },
        "note": "Raw tracked-size savings apply to the current branch/tree only after generated runtime files are removed from Git tracking. Existing historical blobs remain until an optional later history rewrite.",
    }
    if report_path:
        write_pretty_json(report_path, report)
    return report


def main() -> None:
    ap = argparse.ArgumentParser()
    sub = ap.add_subparsers(dest="command", required=True)

    p = sub.add_parser("build-source", help="Build compact canonical source from a verified runtime directory")
    p.add_argument("--runtime-dir", required=True, type=Path)
    p.add_argument("--output", required=True, type=Path)
    p.add_argument("--baseline-commit", default=BASELINE_COMMIT)

    p = sub.add_parser("generate-runtime", help="Generate hsk runtime from canonical source")
    p.add_argument("--source", required=True, type=Path)
    p.add_argument("--output", required=True, type=Path)
    p.add_argument("--pretty", action="store_true")

    p = sub.add_parser("verify", help="Verify source round-trip against a runtime directory")
    p.add_argument("--source", required=True, type=Path)
    p.add_argument("--baseline-runtime", required=True, type=Path)
    p.add_argument("--generated", required=True, type=Path)
    p.add_argument("--report", required=True, type=Path)

    args = ap.parse_args()
    if args.command == "build-source":
        manifest = build_source(args.runtime_dir, args.output, args.baseline_commit)
        print(json.dumps({"status": "PASS", "source": str(args.output), "counts": manifest["counts"]}, ensure_ascii=False, indent=2))
    elif args.command == "generate-runtime":
        result = generate_runtime(args.source, args.output, pretty=args.pretty)
        print(json.dumps({"status": "PASS", "output": str(args.output), **result}, ensure_ascii=False, indent=2))
    elif args.command == "verify":
        result = verify(args.source, args.baseline_runtime, args.generated, args.report)
        print(json.dumps(result, ensure_ascii=False, indent=2))
        raise SystemExit(0 if result["status"] == "PASS" else 2)


if __name__ == "__main__":
    main()
